
name: CI/CD MonoRepo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push BACK
        run: |
          docker build -t ghcr.io/${{ github.repository }}/back ./back
          docker push ghcr.io/${{ github.repository }}/back

      - name: Build & Push FRONT
        run: |
          docker build -t ghcr.io/${{ github.repository }}/front ./front
          docker push ghcr.io/${{ github.repository }}/front

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/app
            docker pull ghcr.io/${{ github.repository }}/back
            docker pull ghcr.io/${{ github.repository }}/front
            docker compose up -d